
#1)დაწერეთ პროგრამა, რომელიც ითხოვს მომხმარებლის სახელს და ამის შემდეგ ბეჭდავს: "გამარჯობა, სახელი!"
your_name=input("please enter your name here: ")
print("hello"+your_name+"!")

#2)მომხმარებელს შემოატანინეთ მასზე ინფორმაცია და ეს ყველაფერი ერთ print-ში დაბეჭდეთ
about_you=input("please enter about you here:")
print(about_you)

#3)შემოატანინეთ მომხარებელს პაროლი და დაბეჭდეთ ეგ პაროლი თუ შემოტანილი 
#პაროლი უდრის თქვენთვის სასურველ პაროლს მაშინ უნდა გამოიტანოს 
# True თუ არადა False
your_password=input("please enter random password here: ")
print(your_password)
my_password="password"
print("is my password identical to your? "+your_password == my_password)
true_or_right=input("is my password identical to your password? : ")

